dist: bionic
language: python

python:
  - 3.6

before_install:
  - sudo add-apt-repository -y ppa:lopin/openconnect-globalprotect
  - sudo apt-get -y update
  - sudo apt-get -y install lftp openconnect imagemagick jpegoptim optipng

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm -rf public || exit 0

script:
  - python zotero/update.py
  - hugo

after_success:
  - hugo -d site
  - ./optimize.sh
  - ./deploy.sh
