language: python

python:
  - 3.6

install:
  - sudo apt-get install lftp
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.1/hugo_0.40.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - rm -rf public || exit 0

script:
  - python zotero/update.py
  - hugo

after_success:
  - hugo -d site
  - ./deploy.sh
  
