---
baseurl: "https://spell.ulb.be/"
title: "Spatial Epidemiology Lab"
languageCode: "en-us"
config: "config.yaml"
metaDataFormat: "yaml"
relativeURLs: true
canonifyURLs: true

theme: "spell"

menu:
  main:
    - Name: "News"
      Weight: 1
      Identifier: "news"
      URL: "/news/"
    - Name: "Team"
      Weight: 2
      Identifier: "team"
      URL: "/person/"
    - Name: "Topics"
      Weight: 3
      Identifier: "topics"
      URL: "/"
    - Name: "Diseases risk mapping"
      Weight: 12
      Identifier: "diseases-risk-mapping"
      URL: "/subject/diseases-risk-mapping/"
      parent: "topics"
    - Name: "Modelling biological invasions"
      Weight: 11
      Identifier: "modelling-biological-invasions"
      URL: "/subject/modelling-biological-invasions/"
      parent: "topics"
    - Name: "Landscape phylogeography"
      Weight: 10
      Identifier: "landscape-phylogeography"
      URL: "/subject/landscape-phylogeography/"
      parent: "topics"
    - Name: "Projects"
      Weight: 4
      Identifier: "projects"
      URL: "/page/projects"
    - Name: "Publications"
      Weight: 5
      Identifier: "publications"
      URL: "/page/publications/"
    - Name: ""
      Pre: '<i class="fa fa-map-marker-alt"></i>'
      Weight: 6
      Identifier: "contact"
      URL: "/page/access/"

params:
  brand: SpELL
  description: "At the **Spatial Epidemiology Lab** (SpELL), we study the effect of spatial factors on the **emergence, spread, persistence and evolution** of **diseases** and **invasive species**. The understanding of key spatial factors, such as climatic, ecological or anthropogenic variables, and their integration into spatial and/or molecular approaches is used to **predict the geographical distribution of risk** and **the environmental factors impacting the dispersal history and dynamic of pathogen spreads**, which can contribute to better targetted **prevention, surveillance and control measures**. We also work toward the development, improvement and application of methods in **[spatial modelling of biological invasions](https://spell.ulb.be/subject/modelling-biological-invasions/)**, **[ecological niche modelling for risk mapping](https://spell.ulb.be/subject/disease-risk-mapping/)**, and **[landscape phylogeography](/subject/landscape-phylogeography)**. The SpELL is also involved in the assembly of large-scale data sets on **[farm animals](/subject/disease-risk-mapping/)** and in studies dedicated to the **[conservation of insect pollinators](https://spell.ulb.be/news/nature_bombus/)**."

imaging:
  resampleFilter: "box"
  quality: 75
  anchor: "smart"

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
  goldmark:
    renderer:
      unsafe: true

---
