---
baseurl: "https://spell.ulb.be/"
title: "Spatial Epidemiology Lab"
languageCode: "en-us"
config: "config.yaml"
metaDataFormat: "yaml"
relativeURLs: true
canonifyURLs: true

theme: "spell"

menu:
  main:
    - Name: "News"
      Weight: 1
      Identifier: "news"
      URL: "/news/"
    - Name: "Team"
      Weight: 2
      Identifier: "team"
      URL: "/person/"
    - Name: "Topics"
      Weight: 3
      Identifier: "topics"
      URL: "/"
    - Name: "Landscape phylogeography"
      Weight: 12
      Identifier: "landscape-phylogeography"
      URL: "/subject/landscape-phylogeography/"
      parent: "topics"
    - Name: "Livestock diseases"
      Weight: 10
      Identifier: "livestock-disease"
      URL: "/subject/livestock-disease/"
      parent: "topics"
    - Name: "Mapping Livestock"
      Weight: 11
      Identifier: "mapping-livestock"
      URL: "/subject/mapping-livestock/"
      parent: "topics"
    - Name: "Mapping human population"
      Weight: 13
      Identifier: "mapping-human-population"
      URL: "/subject/mapping-human-population/"
      parent: "topics"
    - Name: "Modelling geographical invasions"
      Weight: 14
      Identifier: "modelling-geographical-invasions"
      URL: "/subject/modelling-geographical-invasions/"
      parent: "topics"
    - Name: "Projects"
      Weight: 4
      Identifier: "projects"
      URL: "/page/projects"
    - Name: "Publications"
      Weight: 5
      Identifier: "publications"
      URL: "/page/publications/"
    - Name: ""
      Pre: '<i class="fa fa-map-marker-alt"></i>'
      Weight: 6
      Identifier: "contact"
      URL: "/page/access/"


params:
  brand: SpELL
  description: "**Spatial epidemiology** studies the effect of spatial factors on the **emergence, spread, persistence and evolution** of **[diseases](/subject/livestock-disease/)** and **[invasive species](/subject/modelling-geographical-invasions/)**. The understanding of key spatial factors, such as environmental or anthropogenic  variables, and their integration into spatial models is used to **predict the geographical distribution of risk**, which can contribute to better targetted **prevention, surveillance and control measures**. We also work toward the improvement of methods in **spatial modelling** and **[landscape phylogeography](/subject/landscape-phylogeography)**, and of large-scale data sets on **[human](/subject/mapping-human-population/)** and **[farm animals](/subject/mapping-livestock/)**."  

imaging:
  resampleFilter: "box"
  quality: 75
  anchor: "smart"
---
